In [40]:
import kagglehub
import pandas as pd

In [41]:
path = kagglehub.dataset_download('jasminemohamed2545/berber-english-160k-parallel-sentences-for-nlp')
print(path)

C:\Users\lassa\.cache\kagglehub\datasets\jasminemohamed2545\berber-english-160k-parallel-sentences-for-nlp\versions\1

In [42]:
df = pd.read_table('ber.txt')
df

,Go.,Ṛuḥ.,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)
0,Hi.,Azul.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1,Hi.,Azul fell-ak.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2,Hi.,Azul fell-am.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3,Hi.,Azul fell-awen.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4,Hi.,Azul fell-awent.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
...,...,...,...
160877,"One of my favorite quotes by Mark Twain is, ""I...",Yiwet seg tnebdurin-inu timenyafin n Mark Twai...,CC-BY 2.0 (France) Attribution: tatoeba.org #6...
160878,If you talk to a man in a language he understa...,Mer ad as-temmeslayeḍ i umdan s tutlayt i ifeh...,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
160879,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160880,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160881,Doubtless there exists in this world precisely...,Ulac ccek dakken yal argaz yesɛa tameṭṭut ay t...,CC-BY 2.0 (France) Attribution: tatoeba.org #7...

In [43]:
df.dtypes

Go.                                                                                object
Ṛuḥ.                                                                               object
CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)    object
dtype: object

In [44]:
# renaming columns
df.columns = ['english', 'amazigh', 'license']
df.head()

  english           amazigh                                            license
0     Hi.             Azul.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1     Hi.     Azul fell-ak.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2     Hi.     Azul fell-am.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3     Hi.   Azul fell-awen.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4     Hi.  Azul fell-awent.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...

In [45]:
# removing license column 
df = df.drop(columns=['license'])
df.head()

  english           amazigh
0     Hi.             Azul.
1     Hi.     Azul fell-ak.
2     Hi.     Azul fell-am.
3     Hi.   Azul fell-awen.
4     Hi.  Azul fell-awent.

In [46]:
# removing periods 
df['english'] = df['english'].str.replace('.', '', regex=False)
df['amazigh'] = df['amazigh'].str.replace('.', '', regex=False)
df.head()

  english          amazigh
0      Hi             Azul
1      Hi     Azul fell-ak
2      Hi     Azul fell-am
3      Hi   Azul fell-awen
4      Hi  Azul fell-awent