In [19]:
import os
import kagglehub
import pandas as pd

In [33]:
path = kagglehub.dataset_download('jasminemohamed2545/berber-english-160k-parallel-sentences-for-nlp')
print(path)

C:\Users\lassa\.cache\kagglehub\datasets\jasminemohamed2545\berber-english-160k-parallel-sentences-for-nlp\versions\1

In [ ]:
pd.read_table('ber.txt')

,Go.,Ṛuḥ.,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)
0,Hi.,Azul.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1,Hi.,Azul fell-ak.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2,Hi.,Azul fell-am.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3,Hi.,Azul fell-awen.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4,Hi.,Azul fell-awent.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
...,...,...,...
160877,"One of my favorite quotes by Mark Twain is, ""I...",Yiwet seg tnebdurin-inu timenyafin n Mark Twai...,CC-BY 2.0 (France) Attribution: tatoeba.org #6...
160878,If you talk to a man in a language he understa...,Mer ad as-temmeslayeḍ i umdan s tutlayt i ifeh...,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
160879,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160880,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160881,Doubtless there exists in this world precisely...,Ulac ccek dakken yal argaz yesɛa tameṭṭut ay t...,CC-BY 2.0 (France) Attribution: tatoeba.org #7...

In [39]:
df = pd.read_table('ber.txt')

In [40]:
df

,Go.,Ṛuḥ.,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)
0,Hi.,Azul.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1,Hi.,Azul fell-ak.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2,Hi.,Azul fell-am.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3,Hi.,Azul fell-awen.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4,Hi.,Azul fell-awent.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
...,...,...,...
160877,"One of my favorite quotes by Mark Twain is, ""I...",Yiwet seg tnebdurin-inu timenyafin n Mark Twai...,CC-BY 2.0 (France) Attribution: tatoeba.org #6...
160878,If you talk to a man in a language he understa...,Mer ad as-temmeslayeḍ i umdan s tutlayt i ifeh...,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
160879,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160880,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160881,Doubtless there exists in this world precisely...,Ulac ccek dakken yal argaz yesɛa tameṭṭut ay t...,CC-BY 2.0 (France) Attribution: tatoeba.org #7...

In [41]:
df.head(10)

,Go.,Ṛuḥ.,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)
0,Hi.,Azul.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1,Hi.,Azul fell-ak.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
2,Hi.,Azul fell-am.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
3,Hi.,Azul fell-awen.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4,Hi.,Azul fell-awent.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
5,Hi.,ⴰⵣⵓⵍ.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
6,Hi.,azul,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
7,Run!,Azzel!,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
8,Run!,ⴰⵣⵣⵍ,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
9,Run.,Azzel.,CC-BY 2.0 (France) Attribution: tatoeba.org #4...

In [42]:
df.tail(3)

,Go.,Ṛuḥ.,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)
160879,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160880,You can't view Flash content on an iPad. Howev...,Ur tezmired ara ad twalid agbur n Flash deg us...,CC-BY 2.0 (France) Attribution: tatoeba.org #9...
160881,Doubtless there exists in this world precisely...,Ulac ccek dakken yal argaz yesɛa tameṭṭut ay t...,CC-BY 2.0 (France) Attribution: tatoeba.org #7...

In [43]:
df.shape

(160882, 3)

In [44]:
df.count()

Go.                                                                                160882
Ṛuḥ.                                                                               160882
CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)    160882
dtype: int64

In [46]:
df.describe()

,Go.,Ṛuḥ.,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)
count,160882,160882,160882
unique,84167,150056,160882
top,Go home now.,Ur yettett ara waya.,CC-BY 2.0 (France) Attribution: tatoeba.org #7...
freq,56,14,1

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160882 entries, 0 to 160881
Data columns (total 3 columns):
 #   Column                                                                           Non-Null Count   Dtype
---  ------                                                                           --------------   -----
 0   Go.                                                                              160882 non-null  object
 1   Ṛuḥ.                                                                             160882 non-null  object
 2   CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #8325200 (Yagurten)  160882 non-null  object
dtypes: object(3)
memory usage: 3.7+ MB